### ISSUE TITLE
None of the PHP Scripts Work

### ISSUE THREAD

**Issue by manicslothpdx** [jamf/NetSUS#77] opened 2016-07-29 00:24 UTC
After running the NetSUS 4.1 installer on RHEL 6.7, I can log into the web GUI. However, I cannot change any settings such as any of the user passwords or any of the date and time settings. The web GUI seems to indicate that saving these settings was successful, but none of the settings are retained. Made sure SELinux was disabled, tested various wide open permissions, no change.

**Comment by jtrutwin** [comment] 2016-07-29 13:40
Do you have redhat-lsb-core installed?  If so I bet you're running into my 2-year old bug...  Nearly all those PhP scripts reference adminHelper.sh somehow and the OS detection in that script is still flawed.

https://github.com/jamf/NetSUS/issues/35

Frustrating...

**Comment by jtrutwin** [comment] 2016-07-29 13:41
And here we are in 2016 still having to disable selinux to get apps to work...  :/

**Comment by manicslothpdx** [comment] 2016-08-24 21:43
I'm going to close this issue. We moved on to CentOS 7 and I no longer have any test VMs running RHEL 6. After running the installer script on CentOS 7, everything appears to run correctly. I did not have to force the adminHelper.sh script to select a specific version of Linux. The installer script leaves SELinux set to permissive after a restart. So, my point is, on CentOS 7, I no longer have any issues.

**Comment by jtrutwin** [comment] 2016-08-25 15:39
Likely your centos7 install didn't include redhat-lsb-core - mine did.  I would say the issue is still present on either rhel/centos 6/7 depending on whether  this particular package is installed.

That said it doesn't seem like anyone cares to fix it...

Good luck with your install.

**Comment by macmule** [comment] 2016-11-18 10:09
@manicslothpdx thanks for the update. I'll close this off.

**Closed by macmule** 2016-11-18 10:09 UTC
