### ISSUE TITLE
Ubuntu 12.04: netatalk is not installed successfully with the 3.0 standalone installer.

### ISSUE THREAD

**Issue by trevorwagner** [jamf/NetSUS#32] opened 2014-05-13 17:48 UTC
The user guide outlines that it should be possible for users to access an AFP share on the NetSUS server.

Under Linux, AFP service requires netatalk.  In Ubuntu, this requires that the package netatalk be installed. 

When the current 3.0 standalone installer (the coppy of the installer linked to from the front page) is run under Ubuntu LTS 12.04 server, however, netatalk does not appear to be installed as expected.

### Steps to Reproduce

1. Start with a machine running a clean installation of Ubuntu LTS 12.04 Server.  Make sure all of the packages are updated with apt-get.

2. On the clean Ubuntu machine from step 1, run the NetSUS 3.0 standalone installer linked to from the front page of this project.

3. Attempt to locate netatalk.  I did this by running `$ dpkg-query -l netatalk`.  If netatalk is not installed, this command returns an error message that no packages matching netatalk were found; otherwise, it returns name, version number, description, and other information for the currently-installed version of the netatalk package.  Another easy way to do this is to look at /etc/netatalk: on a clean system this folder should exist only if netatalk is installed.

### Notes

My (oblique) understanding is that it appears NetBoot also requires netatalk (somehow).

I'm not reproducing this in Ubuntu LTS Server 10.04.  I'm only reproducing this in 12.04.

I cannot test this in an installer from a copy of NetSUS cloned from this repository (last checkin 152370d5bdfd71a0187d09f04b0b200fb0f54a04) due to #28.

My test machines are VirtualBox VMs, on a host running under OS X 10.9.2.

**Comment by StevenStrand** [comment] 2015-10-24 03:00
Closed as cannot reproduce.

**Closed by StevenStrand** 2015-10-24 03:00 UTC
