### ISSUE TITLE
Ubuntu 12.04: after installing and reboot, /var/appliance/dialog.sh fails in a loop on system startup.

### ISSUE THREAD

**Issue by trevorwagner** [jamf/NetSUS#22] opened 2014-05-08 07:42 UTC
If I install NetSUS under a clean installation of Ubuntu LTS Server 12.04, then reboot the machine, I observe upon reboot that a loop occurs where /var/appliance/dialog.sh posts (and repeats) an error message (that the command "dialog" was not found):

```/var/appliances/dialog.sh: 21: /var/appliances/dialog.sh: dialog: not found```

When this happens, I'm observing that the system is still responsive (and that I can connect to the system via SSH and issue commands).  When I evaluate currently running processes with top, though, I'm observing that dialog.sh occupies 99.9% of the system CPU.

If I'm correct, this appears to occur because dialog is not installed by default in Ubuntu LTS Server 12.04.  See my notes (below) for more information.

### Steps to Reproduce

1. Run a clean installation of Ubuntu LTS Server 12.04.  Make sure all available updates have been applied with aptitude.

2. Per the instructions in the User Guide, install NetSUS from the standalone installer.

3. Reboot the system.  Once the system reboots (while the OS is loading), note the output that displays on the screen.

### Notes

I'm only observing this under Ubuntu LTS Server 12.04.  I'm not observing it at all under LTS Server 10.04, and I'm not reproducing it under CentOS 6.5.  I do not currently have a copy of RHEL 6.4 (or later) that I can test this with.

If I install the package dialog (`# apt-get install dialog`) between steps 1 and 2 in my steps to reproduce, I'm able to follow the rest of the STR without reproducing this behavior.

In the interest of full disclosure (and regardless of whether it seems related), there were three things in my runtime environment that were exceptions to a 100% clean installation:

- I am using static IP (and not DHCP) in my network configuration.
- I have the ssh package installed (and sshd running).
- When installing the system I elected not to use LVM (I used a traditional HD configuration).

It also might be worth noting that I reproduced this in a VirtualBox (v 4.3.10 r93012) virtual machine, with a host machine running under OS X 10.9.1.

**Comment by StevenStrand** [comment] 2015-10-23 18:19
Closed as unable to reproduce.

**Closed by StevenStrand** 2015-10-23 18:19 UTC
